language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.3"
install: mvn install -DskipTests=true -Dgpg.skip=true
before_script:
  - psql -c 'create database javadocio_badges_test;' -U postgres
  - psql javadocio_badges_test < src/main/resources/sql/init.db
script: DATABASE_URL=postgres://postgres@localhost/javadocio_badges_test mvn test

